[package]
name = "ChainTicket"
version = "0.1.0"

[addresses]
ticketchain = "0x2339acd68a5b699c8bfefed62febcf497959ca55527227e980c56031b3bfced9"

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "movement" }
